"""Deterministic, clearly-labelled readouts for the MR60BHA2 radar's bench data.

This module is bench/research only. Its output always carries an explicit
non-medical disclaimer and is built deterministically from captured radar
samples — never generated by an LLM — so a small local model can never
fabricate or misreport a breathing or heart rate. Nothing here is a medical or
safety signal, and none of it asserts anything about the baby's wellbeing.
"""

from __future__ import annotations

import math
from collections.abc import Iterable, Sequence

from .models import Event
from .sensors import RADAR_HEART_RATE_KEY, RADAR_RESPIRATORY_KEY

RADAR_VITALS_DISCLAIMER = (
    "raw radar bench data, not a medical or safety signal, and not clinically "
    "validated"
)


def format_radar_reading(reading: dict[str, object]) -> str:
    """One-line labelled readout of a single live radar sample."""
    parts: list[str] = []
    if "person_present" in reading:
        parts.append("present" if reading["person_present"] else "no presence")
    if "target_count" in reading:
        parts.append(f"{reading['target_count']} target(s)")
    if "target_distance_cm" in reading:
        parts.append(f"{_g(reading['target_distance_cm'])} cm")
    if "room_illuminance_lx" in reading:
        parts.append(f"{_g(reading['room_illuminance_lx'])} lux")
    has_vital = RADAR_RESPIRATORY_KEY in reading or RADAR_HEART_RATE_KEY in reading
    if RADAR_RESPIRATORY_KEY in reading:
        parts.append(f"breathing {_g(reading[RADAR_RESPIRATORY_KEY])}/min")
    if RADAR_HEART_RATE_KEY in reading:
        parts.append(f"heart {_g(reading[RADAR_HEART_RATE_KEY])} bpm")
    if not parts:
        return "no radar data yet"
    line = ", ".join(parts)
    if has_vital:
        # Keep the non-medical label on the line itself, so a single line read out
        # of context (redirected output, a log) can never look like a vital sign.
        line += "  [raw bench data, not a medical signal]"
    return line


def summarise_radar_vitals(samples: Sequence[dict[str, object]]) -> str | None:
    """A deterministic, labelled period summary of the radar's vital-sign values.

    Returns None when no respiratory or heart-rate samples are present, so the
    caller simply says nothing rather than implying data it does not have. The
    summary leads with the non-medical disclaimer and only reports the captured
    numbers — it never interprets them or asserts the baby is well.
    """
    respiratory = _numeric(samples, RADAR_RESPIRATORY_KEY)
    heart = _numeric(samples, RADAR_HEART_RATE_KEY)
    if not respiratory and not heart:
        return None

    bits: list[str] = []
    if respiratory:
        bits.append(_stat_phrase("breathing rate", respiratory, "per minute"))
    if heart:
        bits.append(_stat_phrase("heart rate", heart, "beats per minute"))
    return f"Radar vitals — {RADAR_VITALS_DISCLAIMER}: " + "; ".join(bits) + "."


def summarise_radar_vitals_from_events(events: Iterable[Event]) -> str | None:
    """Build the labelled vitals summary from a run's environment_sample events."""
    samples = [
        event.details for event in events if event.kind == "environment_sample"
    ]
    return summarise_radar_vitals(samples)


def _numeric(samples: Sequence[dict[str, object]], key: str) -> list[float]:
    values: list[float] = []
    for sample in samples:
        value = sample.get(key)
        if isinstance(value, bool):
            continue
        if isinstance(value, (int, float)) and math.isfinite(value):
            values.append(float(value))
    return values


def _stat_phrase(label: str, values: list[float], unit: str) -> str:
    low = min(values)
    high = max(values)
    average = sum(values) / len(values)
    sample_word = "sample" if len(values) == 1 else "samples"
    return (
        f"{label} averaged {average:.0f} {unit} "
        f"(range {_g(low)} to {_g(high)}, {len(values)} {sample_word})"
    )


def _g(value: object) -> str:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return str(value)
    if not math.isfinite(value):
        return "—"
    return f"{float(value):g}"
